version: "3.9"
services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.local
  #   restart: always
  #   env_file: .env
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  #   volumes:
  #     - "./frontend/src:/usr/src/app/src"
  #   networks:
  #     - bp-network
  #   command: "npm start"
  backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile.local
      restart: always
      env_file: .env
      volumes:
        - ./backend:/svr/app
        - /svr/app/node_modules
      networks:
        - bp-network
      ports:
        - "${BACKEND_PORT}:${BACKEND_PORT}"
      depends_on:
        - bp-mongo-db
      links:
        - bp-mongo-db
  bp-mongo-db:
    image: mongo:latest
    restart: always
    container_name: bp-mongo-db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./backend/storage/db:/data/db
    networks:
      - bp-network
networks:
  bp-network:
    driver: bridge